# Name of your site (displayed in the header)
name: Machine Init 
description: Information Security, Infrastructure and Networking Blog
avatar: /images/ironman-bw.png
footer-links:
  email: info.machineinit@gmail.com
  github: Mrmachine3 
  linkedin: anthonymrodriguezcisa3
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# disqus: machineinit

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:
  id: UA-129648495-1 # Add tracking id  with Google Analytics
  anonymizeIp: false # set true - to anonymize tracking of IP

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://mrmachine3.github.io)
baseurl: ""

# !! You don't need to change any of the configuration flags below !!
permalink: /:title/
version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-time-to-read # Display a time to read

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
